name: CI

on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: nixbuild/nix-quick-install-action@v5
      - uses: nixbuild/nixbuild-action@v4
        with:
          nixbuild_ssh_key: ${{ secrets.NIXBUILD_SSH }}
      - run: |
          nix-build -I nixpkgs=channel:nixos-20.03
          basename $(readlink ./result) | cut -d - -f1
